import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import QueryProvider from "@/components/providers/QueryProvider";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <QueryProvider>
            <Navbar />
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
          </QueryProvider>
        </main>
      </body>
    </html>
  );
}
